#!/bin/bash
echo '********************'
echo 'pulling git_repo'
echo '********************'

mkdir -p /usr/local/src

chdir /usr/local/src

git clone git://github.com/lyondhill/voltometer.git

chdir /usr/local/src/voltometer

echo '********************'
echo 'now run the bundle command'
echo '********************'

chdir /usr/local/src/voltometer

bundle install

rake install

echo '********************'
echo 'Finally move the startup script'
echo '********************'

curl -o /etc/init/voltometer.conf https://raw.github.com/lyondhill/voltometer/master/etc/init/voltometer.conf

service voltometer start

echo '********************'
echo '--------------------'
echo 'FINNISHED!'
echo '--------------------'
echo '********************'




